
version: '3.8'
services:
  # Servidor para la Django app
  backend_blog:
   container_name: bt_transfer_ms_blog
   build: .
   command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
   volumes:
    - .:/app
   ports:
    - 8001:8001
   depends_on:
    - db_blog
    - redis
  
  # Base de datos local (PostgreSQL)
  db_blog:
   image: postgres
   container_name: django_blog_api_postgresql
   restart: always
   environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: holahola
   ports:
    - 5433:5432
   volumes:
      - .dbdata:/var/lib/postgresql

  # Redis Cache
  redis:
    image: redis
    container_name: django_blog_api_redis
    ports:
      - 6380:6379



  

